# .github/workflows/base.yml
name: Build
on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # TODO
  # - one pre-job to read nox tests matrix
  # see https://tomasvotruba.com/blog/2020/11/16/how-to-make-dynamic-matrix-in-github-actions/
  run_all_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]  # , macos-latest, windows-latest]
        # all nox sessions
        nox_session: ["tests-2.7(env='pytest2.x')", "tests-3.7(env='pytest-latest')"]
        include:
          # add a variable for reports + doc publish
          - os: ubuntu-latest
            nox_session: "tests-3.7(env='pytest-latest')"
            name_suffix: "+ publish doc and reports"
    name: Run all tests on OS ${{ matrix.os }} and env ${{ matrix.nox_session }} ${{ matrix.name_suffix }}
    runs-on: ${{ matrix.os }}
    steps:
      # 0) check the context of this job
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      # 1) Checkout a copy of the repo
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # so that gh-deploy works

      # 2) Setup python version 3.8
      # - name: Install python 3.7 for nox
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.7
      #     architecture: x64
      # 2) Add Conda to PATH
      # - name: Add conda to system path
      #   run: |
      #     # $CONDA is an environment variable pointing to the root of the miniconda directory
      #     echo $CONDA/bin >> $GITHUB_PATH
      # 2) Setup conda
      - name: Install conda v3.7
        uses: conda-incubator/setup-miniconda@v2
        with:
          # auto-update-conda: true
          python-version: 3.7
          activate-environment: noxenv
      - name: Initial Conda info
        shell: bash -l {0}  # so that conda works
        run: conda info
      - name: Initial Conda list
        shell: bash -l {0}  # so that conda works
        run: conda list

      # 3) Install nox
      - name: Install noxfile requirements
        shell: bash -l {0}  # so that conda works
        run: pip install -r noxfile-requirements.txt
      - name: Conda list after noxfile requirements installation
        shell: bash -l {0}  # so that conda works
        run: conda list

      # 4) Run nox test session for current build matrix position
      - name: Run nox ${{ matrix.nox_session }}
        shell: bash -l {0}  # so that conda works
        # env:
        #   EXCH_AKEY: ${{ secrets.EXCH_AKEY }}
        run: nox -s "${{ matrix.nox_session }}"

      # 5) publish reports so that they can be deployed with doc in next job
      - name: Share reports with other jobs
        # if: matrix.nox_session == '...': not needed, if empty wont be shared
        uses: actions/upload-artifact@master
        with:
          name: reports_dir
          path: ./docs/reports

  publish_release:
    needs: run_all_tests
    runs-on: ubuntu-latest
    steps:
      # 0) check the context of this job
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      # 1) Checkout a copy of the repo
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # so that gh-deploy works

      # 1) retrieve the reports generated previously
      - name: Retrieve reports
        uses: actions/download-artifact@master
        with:
          name: reports_dir
          path: ./docs/reports

      # 2) Setup python version 3.8
#      - name: Install python 3.7 for nox
#        uses: actions/setup-python@v1
#        with:
#          python-version: 3.7
#          architecture: x64
      # 2) Add Conda to PATH
#      - name: Add conda to system path
#        run: |
#          # $CONDA is an environment variable pointing to the root of the miniconda directory
#          echo $CONDA/bin >> $GITHUB_PATH
      # 2) Setup conda
      - name: Install conda v3.7
        uses: conda-incubator/setup-miniconda@v2
        with:
          # auto-update-conda: true
          python-version: 3.7
          activate-environment: noxenv
      - name: Initial Conda info
        shell: bash -l {0}  # so that conda works
        run: conda info
      - name: Initial Conda list
        shell: bash -l {0}  # so that conda works
        run: conda list

      # 3) Install nox
      - name: Install noxfile requirements
        shell: bash -l {0}  # so that conda works
        run: pip install -r noxfile-requirements.txt
      - name: Conda list after noxfile requirements installation
        shell: bash -l {0}  # so that conda works
        run: conda list

      # -------------- only on Ubuntu + MAIN PUSH (no pull request, no tag) -----------

      # 5) Publish the doc and test reports
      - name: \[not on TAG\] Publish documentation, tests and coverage reports
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads')  # startsWith(matrix.os,'ubuntu')
        shell: bash -l {0}  # so that conda works
        run: nox -s publish

      # 6) Publish coverage report
      - name: \[not on TAG\] Create codecov.yaml with correct paths
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads')  # startsWith(matrix.os,'ubuntu')
        shell: bash
        run: |
          cat << EOF > codecov.yml
          # codecov.yml
          fixes:
            - "/home/runner/work/smarie/python-pytest-harvest/::" # Correct paths
          EOF
      - name: \[not on TAG\] Publish coverage report
        if: startsWith(matrix.os,'ubuntu') && github.event_name == 'push' && startsWith(github.ref, 'refs/heads')
        uses: codecov/codecov-action@v1
        with:
          files: ./docs/reports/coverage/coverage.xml

      # -------------- only on Ubuntu + TAG PUSH (no pull request) -----------

      # 7) Create github release and build the wheel
      - name: \[TAG only\] Build wheel and create github release
        if: startsWith(matrix.os,'ubuntu') && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        shell: bash -l {0}  # so that conda works
        run: nox -s release -- ${{ secrets.GITHUB_TOKEN }}

      # 8) Publish the wheel on PyPi
      - name: \[TAG only\] Deploy on PyPi
        if: startsWith(matrix.os,'ubuntu') && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  delete-artifacts:
    needs: publish_release
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0 # Setting this to 0 will delete all artifacts
